name: 中国电信签到

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js 16.x
        uses: actions/setup-node@v5
        with:
          node-version: 16.x

      - name: npm install
        run: npm install

      - name: 运行电信签到
        # 重点：env 要和 run 同级，缩进两个空格
        env:
          # 强制引用，绝对不会丢
          TELECOM_MOBILE: ${{ secrets.TELECOM_MOBILE }}
          SEND_KEY: ${{ secrets.SEND_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
        run: node function/10000/10000.js
