name: 中国电信签到

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js 16.x
        uses: actions/setup-node@v5
        with:
          node-version: 16.x

      - name: npm install
        run: npm install

      - name: 运行电信签到
        run: node function/10000/10000.js
        env:
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
